apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: eon
data:
  DB_HOST: "34.64.222.199"
  DB_PORT: "3306"
  DB_USER: "eon"
  DB_NAME: "eon"

  PORT: "4000"
  FRONTEND_URL: "https://eon.n-e.kr/"